---
- name: my_server
  hosts: my_server
  become: yes
  tasks:
    - name: "install tuned"
      tasks:
      apt :
       - tuned
      state: present
    - name : "Start tuned"
      systemd:
        name: tuned
        state: present
        enable: yes
